version: 0.2

phases:
  pre_build:
    commands:
       - $(aws ecr get-login --no-include-email --region $CI_REGION)
  build:
    commands:
       - docker build -t hiflask .
  post_build: 
    commands:
       - docker push $REPO_URL:$LATEST_VERSION
       - printf '[{"name":"hiflask","imageUri":"085912648430.dkr.ecr.ap-northeast-1.amazonaws.com/xoxzo/hiflask:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
